data:
    dataset: "Fog"
    image_size: 
    channels: 3
    num_workers: 32
    data_dir: "/home/tanvir/Work/754/project/other_code/WeatherDiffusion"
    train_data_dir: "/home/tanvir/Work/754/project/other_code/WeatherDiffusion/data/fog_train"
    val_data_dir: "/home/tanvir/Work/754/project/other_code/WeatherDiffusion/data/fog_val"
    filelist: "fog.txt"
    val_filelist: "fog_val.txt"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 8
    batch_size: 4
    n_epochs: 420
    n_iters: 2500000
    snapshot_freq: 5000
    validation_freq: 10000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
